name: build-and-test

on:
  push:
    tags-ignore:
      - '*'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['8', '10', '12', '13']
    name: build and test (node ${{ matrix.node }})

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1.2.0
        with:
          node-version: ${{ matrix.node }}
      - run: node --version
      - run: npm ci
      - run: npm test
