name: Deploy

on:
  push:
    tags:
      - '*'
  release:
    types: published

jobs:
  Deploy-To-NPM:
    runs-on: ubuntu-latest
    name: Deploy to NPM

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1.2.0
        with:
          node-version: '10.x'
          registry-url: 'https://registry.npmjs.org'
      - run: node --version
      - run: npm ci
      - run: npm config set @vaju:registry https://registry.npmjs.org
      - run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  Deploy-To-GitHub-Package-Registry:
    runs-on: ubuntu-latest
    name: Deploy to GPR

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1.2.0
        with:
          node-version: '10.x'
          registry-url: 'https://npm.pkg.github.com'
      - run: node --version
      - run: npm ci
      - run: npm config set @vajahath:registry https://npm.pkg.github.com
      - run: npm publish --scope=@vajahath
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
          npm_config_scope: '@vajahath'
